id: P34D7E133
initial_creation_type: input
source_metadata:
  title: Grammar Series
  language: bo
  description: 'Texts related to various aspects of Tibetan grammar and orthography:'
  volume:
    977a1135d55346fe8f4a83e57865ce25:
      title: 'The Magical Wish-Fulfilling Tree: The Essence of Thönmi’s Masterpiece
        ''The Thirty Verses'''
      parent: Orthography
created_at: '2022-03-01T03:44:15.438107'
last_modified_at: '2022-03-01T03:44:15.438109'
statistics:
  total_words: 707
  total_non_words: 124
quality:
  non_words_ratio: 0.18
